import { createApp } from 'vue';
import { initializeDarkMode } from '@/utils/dark-mode';
import 'vant/es/toast/style';
import 'vant/es/dialog/style';
import '@/assets/styles/index.scss';
import App from './App.vue';
import { createPinia } from 'pinia';
import router from '@/router';
initializeDarkMode();
const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
app.use(router);
app.mount('#app');
